server.port=3000

spring.datasource.username=root
spring.datasource.password=20020606Hxy
spring.datasource.url=jdbc:mysql://localhost:3306/kob?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.redis.host=localhost
spring.redis.port=6379
spring.redis.password=123456
spring.redis.database=10